services:
  docker-dp-postgres:
    image: postgres:latest
    container_name: docker-dp-postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env.postgres
    volumes:
      - /home/moheshen/repos/dp/docker-dp/data/db/:/var/lib/postgresql
