services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "chilli"
      POSTGRES_PASSWORD: "S3cur3P@ssw0rd!"
      POSTGRES_DB: "main"
    networks:
      - default
